### ISSUE TITLE
I/O operation on closed file when calling for a "global stop"

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/skill-ovos-filebrowser#13]
```
2023-10-02 16:43:50.591 - skill-ovos-filebrowser.openvoiceos - ERROR - Failed to stop skill: skill-ovos-filebrowser.openvoiceos: I/O operation on closed file.
Traceback (most recent call last):
  File "/home/ovos/.local/lib/python3.10/site-packages/ovos_workshop/skills/base.py", line 2070, in __handle_stop
    if self.stop():
  File "/home/ovos/.local/lib/python3.10/site-packages/skill_ovos_filebrowser/__init__.py", line 187, in stop
    self.udev_thread.stop()
  File "/home/ovos/.local/lib/python3.10/site-packages/pyudev/monitor.py", line 591, in stop
    self.send_stop()
  File "/home/ovos/.local/lib/python3.10/site-packages/pyudev/monitor.py", line 562, in send_stop
    with self._stop_event.sink:
ValueError: I/O operation on closed file.
```

**Comment by JarbasAl** [comment]
skill replaced by https://github.com/OpenVoiceOS/skill-ovos-local-media/
